name: tests-snapshots

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  vitest-snapshots:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        node-version: [18.x, 20.x, 22.x]
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install dependencies
        run: npm ci

      - name: Run snapshot tests
        run: npm run test:snap:run
