name: tests-snapshots

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-wasm:
    name: build wasm
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm

      - name: Install dependencies
        run: npm ci

      - name: Setup Emscripten (emsdk)
        uses: mymindstorm/setup-emsdk@v14
        with:
          version: 3.1.40

      - name: Cache llvm-project source and build
        uses: actions/cache@v4
        with:
          path: |
            ../llvm-project
            ../llvm-project/build-wasm
          key: ${{ runner.os }}-emsdk-3.1.40-llvm-wasm-${{ hashFiles('scripts/bootstrap-llvm-wasm.sh') }}

      - name: Bootstrap LLVM/MLIR for WASM
        run: bash scripts/bootstrap-llvm-wasm.sh

      - name: Build WASM parser
        env:
          LLVM_DIR: ${{ github.workspace }}/../llvm-project/build-wasm
          MLIR_DIR: ${{ github.workspace }}/../llvm-project/build-wasm
        run: bash scripts/build-wasm.sh

      - name: Upload wasm artifacts
        uses: actions/upload-artifact@v4
        with:
          name: wasm-artifacts
          path: |
            wasm/mlir_parser.js
            wasm/mlir_parser.wasm
          if-no-files-found: error

  snapshots:
    name: snapshots (node ${{ matrix.node }})
    runs-on: ubuntu-latest
    needs: build-wasm
    strategy:
      fail-fast: false
      matrix:
        node: [18, 20, 22]
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js ${{ matrix.node }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node }}
          cache: npm

      - name: Install dependencies
        run: npm ci

      - name: Download wasm artifacts
        uses: actions/download-artifact@v4
        with:
          name: wasm-artifacts
          path: wasm

      - name: Run snapshot tests (vitest)
        run: npm run test:snap:run
        env:
          CI: true

      - name: Upload snapshot diffs (on failure)
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          # Make artifact name unique per matrix job and run attempt to avoid 409 conflicts
          name: vitest-snapshots-diff-node-${{ matrix.node }}-run${{ github.run_attempt }}
          path: |
            tests/snapshot/**/__snapshots__/**
            **/vitest-output.log
          if-no-files-found: ignore
