name: tests-node

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-wasm:
    name: Build WASM artifacts
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Setup Emscripten (emsdk)
        uses: mymindstorm/setup-emsdk@v14
        with:
          version: 3.1.40

      - name: Cache llvm-project build
        uses: actions/cache@v4
        with:
          path: |
            ../llvm-project
            ../llvm-project/build-wasm
          key: ${{ runner.os }}-llvm-wasm-${{ hashFiles('scripts/bootstrap-llvm-wasm.sh') }}

      - name: Bootstrap LLVM/MLIR for WASM
        run: |
          bash scripts/bootstrap-llvm-wasm.sh

      - name: Build WASM parser
        env:
          LLVM_DIR: ${{ github.workspace }}/../llvm-project/build-wasm
          MLIR_DIR: ${{ github.workspace }}/../llvm-project/build-wasm
        run: |
          bash scripts/build-wasm.sh

      - name: Upload wasm artifacts
        uses: actions/upload-artifact@v4
        with:
          name: wasm-artifacts
          path: |
            wasm/mlir_parser.js
            wasm/mlir_parser.wasm

  unit-node:
    name: Unit (Node ${{ matrix.node }})
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        node: [18, 20, 22]
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Use Node.js ${{ matrix.node }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node }}
          cache: 'npm'

      - name: Install dependencies
        run: npm install

      - name: Run unit tests
        run: npm run test:ci
        env:
          CI: true

  integration-wasm:
    name: Integration (WASM)
    runs-on: ubuntu-latest
    needs: build-wasm
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Download wasm artifacts
        uses: actions/download-artifact@v4
        with:
          name: wasm-artifacts
          path: wasm

      - name: Install dependencies
        run: npm install

      - name: Run tests (WASM required)
        env:
          CI: true
        run: npm run test:ci
